### ISSUE TITLE
port 80

### ISSUE THREAD

**Issue by ZarinNegah** [elestio/ws-screenshot#2]
Hello
Good time
You wrote a good script

How can I run on port 80 instead of port 3000?

Thank

**Comment by jbenguira** [comment]
Hey ZarinNegah,
with this docker command you can run it on port 80 instead of 3000:

`sudo docker run --name ws-screenshot -d --restart always -p 80:3000 -it elestio/ws-screenshot.slim`

This will expose the service on port 80 of your IP address

**Comment by ZarinNegah** [comment]
thanks for respons
---------
root@screen:~# sudo docker run --name ws-screenshot -d --restart always -p 80:3000 -it elestio/ws-screenshot.slim
docker: Error response from daemon: Conflict. The container name "/ws-screenshot" is already in use by container "f44f294089051e7d77903720fff65ca78f43cef2ba87fe30897f8d8ac96ba83f". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.

**Comment by ZarinNegah** [comment]
thanks for respons
---------
root@screen:~# sudo docker run --name ws-screenshot -d --restart always -p 80:3000 -it elestio/ws-screenshot.slim
docker: Error response from daemon: Conflict. The container name "/ws-screenshot" is already in use by container "f44f294089051e7d77903720fff65ca78f43cef2ba87fe30897f8d8ac96ba83f". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.

**Comment by jbenguira** [comment]
you already have a container with the same name (previous launch I guess)
you can remove it with:
```
docker stop ws-screenshot
docker rm ws-screenshot

```
then start it again with:
`sudo docker run --name ws-screenshot -d --restart always -p 80:3000 -it elestio/ws-screenshot.slim`

**Comment by ZarinNegah** [comment]
> you already have a container with the same name (previous launch I guess)
> you can remove it with:
> 
> ```
> docker stop ws-screenshot
> docker rm ws-screenshot
> ```
> 
> then start it again with:
> `sudo docker run --name ws-screenshot -d --restart always -p 80:3000 -it elestio/ws-screenshot.slim`

thanks dear

Add these features as well
The script is complete

--crop, -c
Crop to the set height

--filename=<template>
Custom filename.

--selector=<element>
Capture DOM element.

--hide=<element>
Hide DOM element. Can be set multiple times.

--css=<string>
Apply custom CSS to the webpage. Specify some CSS or the path to a CSS file.

https://github.com/sindresorhus/pageres-cli

**Comment by jbenguira** [comment]
I'll try to add those options when I have some free time :)

**Comment by ZarinNegah** [comment]
> I'll try to add those options when I have some free time :)

You are a unique programmer
Thankful

Another question
Does the Docker version support parallel requests at the same time?
Or just the version running on nudejs

**Comment by ZarinNegah** [comment]
You are a unique programmer
Thankful

Another question
Does the Docker version support parallel requests at the same time?
Or just the version running on nudejs
