### ISSUE TITLE
Add certificate authority to cert store of browser within docker image

### ISSUE THREAD

**Issue by flikites** [elestio/ws-screenshot#21]
I have a particular use case that requires me to upload a CA to the cert store of the browser that is taking the screenshot. Is this possible to add in? 

If not is their an environment variable similar to the proxy that can be used to ignore cert errors?

**Comment by jbenguira** [comment]
For that particular use case, I recommend you to customize the chrome flags here 
https://github.com/elestio/ws-screenshot/blob/master/API/shared.js#L21

and include this one: --ignore-certificate-errors

this will disable certificate checks

**Comment by FliKites** [comment]
Thank you! ---- On Mon, 14 Nov 2022 17:06:56 -0500  ***@***.***  wrote ----
For that particular use case, I recommend you to customize the chrome flags here
https://github.com/elestio/ws-screenshot/blob/master/API/shared.js#L21
and include this one: --ignore-certificate-errors
this will disable certificate checks
