### ISSUE TITLE
Resource managment

### ISSUE THREAD

**Issue by kingjin94** [elestio/ws-screenshot#29]
I run your great container to store images of more dynamic iframes to store as loading images. It is a great help. Today after testing the project with a few 100 screenshot requests I was a bit stunned to see that there are a lot of open threats and processes left after processing; the container at the moment has 10 GB of RAM with about ~100 open node servers.

Is one supposed to reset this container every few hours or call a certain API end to free resources?

**Comment by jbenguira** [comment]
Hey @kingjin94, thanks for the kind words :)
Indeed on my side in production I do restart the containers automatically on a schedule mainly because of memory leak from Chrome.
