### ISSUE TITLE
Inject JS before screenshot

### ISSUE THREAD

**Issue by YanK-fr** [elestio/ws-screenshot#34]
Hello,

Is it possible to inject JS in page ?
The idea is to remove cookie popup before screenshot. :)

**Comment by jbenguira** [comment]
no it's not possible currently, if you want to implement it you can do that close to here:
https://github.com/elestio/ws-screenshot/blob/a15ce4f4cb725a0e5532b19adbed50169ffd85bc/API/shared.js#L214
