### ISSUE TITLE
Browser resolution and automation detection

### ISSUE THREAD

**Issue by ml-airflow** [elestio/ws-screenshot#38]
This is a great tool and I hope you will keep updating it! 

We have two issues: 

1. when we screenshot responsive sites, no matter what i put in the resx/resy, it keeps showing the mobile/tablet version of the site , even if I put crazy values
2. most sites (but easy to check with reddit.com) that care about this kind of blocking see this browser instance as something automated and pop up protection from it; it doesn't really seem to matter from where I shoot the request

Does either of these sound familiar and are there fixes? 

I guess a follow up for 2. would be; can we add proxy servers (optional) ?

**Comment by jwjacobs88** [comment]
Do you have an example for #1? I'm not able to replicate that issue with a few responsive websites I tried.

For Reddit.com, I am able to screenshot it running locally.

![image](https://github.com/elestio/ws-screenshot/assets/3289919/6b2bff31-233f-42dc-b5c2-60d7dadd2e6f)
