### ISSUE TITLE
Docker Hub arm package

### ISSUE THREAD

**Issue by ElmerLastdrager** [elestio/ws-screenshot#40]
Would it be possible to publish arm64 images to Docker for this project? It would be nice for people that are running an M{1,2,3} Macbook and use ARM64 servers (yes, they exist 😆). Thanks!

**Comment by jbenguira** [comment]
Hey @ElmerLastdrager 
ARM64 image is now available on docker hub with this tag: **elestio/ws-screenshot.slim:latest-arm**

[latest-arm](https://hub.docker.com/layers/elestio/ws-screenshot.slim/latest-arm/images/sha256-b5250263046145b1227b525ec1f2e2dbcc6d8acbe2c7d06eb31e7f88a13b2034?context=explore)
