### ISSUE TITLE
Add Option For Strict waitTime

### ISSUE THREAD

**Issue by SeboKnt** [elestio/ws-screenshot#43]
First of all, thank you for the great project, this is exactly what I was looking for. :)
One feature I miss though is the option to wait a certain amount of time for the screenshot to be taken, even if the web page is already "finished" loading. 

 There is an option to wait a maximum time in milliseconds, but the SC is also executed here before the time has expired, even though the CSS of my website is not yet displayed correctly.

**Comment by jbenguira** [comment]
Hey @SeboKnt, have you tried to increase the time to wait?
please indicate the url as well so I can test it

**Comment by SeboKnt** [comment]
Thanks for the quick reply. Unfortunately the website is hosted in my LAN.  
I am using the docker image elestio/ws-screenshot.slim:latest-arm
I set the time to 16 seconds, but the curl command only took 10 seconds:  
```
$ curl -o screen.png http://192.168.178.69:3000/api/screenshot\?resX\=1200\&resY\=825\&outFormat\=png\&waitTime\=16000\&isFullPage\=false\&dismissModals\=true\&url\=http://192.168.178.73:8123/dashboard-test/0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 39713    0 39713    0     0   3631      0 --:--:--  0:00:10 --:--:-- 10201

```
If I change the other parameters such as the resolution or the FullPage in the url, these are adjusted, but unfortunately not the time. I also had the situation where the maximum time was exceeded and the screenshot took longer. 
```
$ curl -o screen.png http://192.168.178.69:3000/api/screenshot\?resX\=1200\&resY\=825\&outFormat\=png\&waitTime\=2000\&isFullPage\=false\&dismissModals\=true\&url\=http://192.168.178.73:8123/dashboard-test/0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10421    0 10421    0     0   1218      0 --:--:--  0:00:08 --:--:--  2307
```

Or is there something else I'm missing?

**Comment by jbenguira** [comment]
Just tried it on my side with the public demo instance and it's working as expected:

curl -o screen.png "https://backup15.terasp.net/api/screenshot?resX=1280&resY=900&outFormat=jpg&waitTime=16000&isFullPage=false&dismissModals=false&url=https://google.com"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  143k    0  143k    0     0   8667      0 --:--:--  0:00:16 --:--:-- 39269

So I'm not able to replicate your issue
