### ISSUE TITLE
Not found with VM google cloud

### ISSUE THREAD

**Issue by WebdevWebi** [elestio/ws-screenshot#45]
I installed ws-screenshot in a Google Cloud VM, with Ubuntu LTS operating system.

I downloaded all the libraries required by the documentation.
I made my project always active.

Unfortunately, however, when I test the operation via a POST call, I do not receive any screenshot, while with the same configuration performed locally I correctly receive the requested screenshot.

I hypothesized problems with the operating system.
To your knowledge should I boot the VM with a specific operating system?

Thank you!

**Comment by jbenguira** [comment]
No issues with Ubuntu LTS, this is what I also use (but not on GCP)
check what your API call return, maybe your VM is not reachable over internet (firewall issue)

**Comment by WebdevWebi** [comment]
Normally, when testing via PostMan I receive a response with code 200, which leaves me thinking that everything is working and that it is reachable.
In the firewall I set the addresses 0.0.0.0/0 and port 3000, so as to be sure.

The only thing I noticed is that in the JSON that the call returns to me, the value of PuppeteerProcess is 0.

You don't use GCP, what do you use?

**Comment by jbenguira** [comment]
I use Elestio to deploy and run it on Hetzner, Digital Ocean, Vultr, or any other cloud, you can try with this link (there is a free trial):
https://dash.elest.io/deploy?source=cicd&social=dockerCompose&url=https://github.com/elestio-examples/ws-screenshot

Disclaimer: I'm the CTO of Elestio

About your issue on GCP, I recommend you to try the Docker version, it's fully packaged with all dependencies, it's a lot easier to run than the non-docker version

**Comment by WebdevWebi** [comment]
The problem is that I should use this service within an automation in make.com, therefore I need to have the service always online, which is why I aimed to run it via a cloud service.

**Comment by jbenguira** [comment]
Not sure if you are saying that related to docker or to elestio.
Docker run as a daemon in the background, so it's always running.

And deployments on Elestio are also always on and in the cloud :)
If you are not able to make it work in GCP, I definitely recommend you to try the free-trial on elestio, in 3 min you will have a working instance and ready to use.

**Comment by WebdevWebi** [comment]
Ok so do you recommend running it in combination between Docker and Elastio, or are the two things not connected?

**Comment by jbenguira** [comment]
On Elestio it's running the Docker version, It's fully automated including install of docker, running ws-screenshot, DNS, SSL, monitoring/alerts, updates.

**Comment by WebdevWebi** [comment]
Ok, so to get a more complete overview of how Elastio works:
What service do you offer (generally speaking)?
If I wanted to load more scripts into Elastio in the future, would that be possible?
In the case of ws-screenshot, what plan would you recommend? 
Is the link for the free trial the one you already sent me?

Sorry for the many questions, but I need them to have the most complete overview possible.
Thank you!

**Comment by jbenguira** [comment]
Elestio (and not Elastio) is offering fully managed open-source services.
A lot of startups & companies need to use Open source software but lack devops expertise or lack time to maintain that over time. Elestio includes deployment, security, updates, migrations and also human support to deploy & maintain open source software on any cloud provider.

On Elestio we support a large catalog of 350+ open source software, also you can deploy any other software we don't already support or your own frontend/backend source code using our CICD system:
https://docs.elest.io/books/cicd-pipelines

For ws-screenshot I recommend to use 2cpu/4gb of ram, if you plan to make a lot of concurrent API calls then you can upgrade the plan to something with more CPU as needed.

The link I sent is to start deploying ws-screenshot on elestio, you will be prompted to create an account first, after adding a CC you will get free trial credits, and then you can deploy ws-screenshot in few clicks

**Comment by WebdevWebi** [comment]
Browsing this link: https://dash.elest.io/deploy?source=cicd&social=dockerCompose&url=https://github.com/elestio-examples/ws-screenshot, I find myself in the CI/CD configuration page, but First I have to decide which service to upload it to.
In the case of ws-screenshot which service should I choose?
Could you quickly walk me through the setup?

**Comment by jbenguira** [comment]
If you click that link, the software is directly preselected (ws-screenshot)
then you have to select the cloud provider & vm size
I recommend Hetzner with 2cpu/4gb ram
Then click on next until your service is deployed :)

**Comment by WebdevWebi** [comment]
I registered with the ws-screenshot package, it tells me that my account is being verified, will the test credit be loaded following the verification?

**Comment by jbenguira** [comment]
let's continue by email on support@elest.io, this is unrelated to ws-screenshot
