### ISSUE TITLE
Elestio --> HTTP (GET) in Make.com --> Binary Code

### ISSUE THREAD

**Issue by WebdevWebi** [elestio/ws-screenshot#46]
I'm working on an automation in Make.com.
My ws-screenshot is inside Elestio.

I'm making an authenticated GET call within Make.com via an HTTP form and as output I have the Binary Code of the supposed screenshot.
When I go to decode the Binary Code it comes out that the file could be damaged.

Making the exact same call within PostMan I see the screenshot correctly, but in BinaryCode coming out of Make.com it doesn't appear to be correct.

I attach a screenshot of the output.

![Screenshot 2024-12-06 100351](https://github.com/user-attachments/assets/1c6d0934-c458-4e28-87f3-2132893a9ab3)

Could you help me?

**Comment by jbenguira** [comment]
this is correct, The response is the binary of the screenshot
You might instead contact Make.com for help
