### ISSUE TITLE
What is the license

### ISSUE THREAD

**Issue by nilya** [elestio/ws-screenshot#8]
Hi. Thank you for the project.

It has no license. Can you please add it?
It may be either a LICENSE file or just license name in the README.

GitHub has a documentation [on how to choose a license](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository) and [how to add it](https://docs.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository) to the repository.

**Comment by nilya** [comment]
I'll add more details.
We are thinking of using an existing screenshot solution or developing our own solution.

According to our experiments ws-screenshot is pretty good. We want to enhance it (add an XPath parameter to the Api to make screenshot when specified HTML-element will be created instead of just by timeout) and contribute this change back. But we can't use or change it legally without a license.

**Comment by jbenguira** [comment]
Hey Nilya, YW :)
It's now MIT license: https://github.com/elestio/ws-screenshot/blob/master/LICENSE

**Comment by jbenguira** [comment]
> According to our experiments ws-screenshot is pretty good. We want to enhance it (add an XPath parameter to the Api to make screenshot when specified HTML-element will be created instead of just by timeout) and contribute this change back. But we can't use or change it legally without a license.

That would be great :)

**Comment by nilya** [comment]
> Hey Nilya, YW :)
> It's now MIT license: https://github.com/elestio/ws-screenshot/blob/master/LICENSE

Thank you for clarification.
I think we can close this issue. We will open a new one when we will be ready with the XPath parameter.
